- name: Add Host to data dVS - MSSQL
  when: item.cluster == 'WDMMSSQL-Cluster'
  vmware_dvs_host:
    hostname: "{{ vcenter }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ item.esxi_hostname }}.{{ domainname }}"
    switch_name: "{{ data_dvswitch }}"
    vmnics:
        - vmnic4
        - vmnic5
    state: present
    validate_certs: no
  with_items:
   - "{{ vars_hosts }}"
  delegate_to: localhost
- name: Add Host to data dVS - Apps
  when: item.cluster == 'WDMApps-Cluster'
  vmware_dvs_host:
    hostname: "{{ vcenter }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ item.esxi_hostname }}.{{ domainname }}"
    switch_name: "{{ data_dvswitch }}"
    vmnics:
        - vmnic4
        - vmnic10
    state: present
    validate_certs: no
  with_items:
   - "{{ vars_hosts }}"
  delegate_to: localhost