- name: Add Host to vMotion dVS
  when: item.cluster == 'WDMApps-Cluster' or item.cluster == 'WDMMSSQL-Cluster'
  vmware_dvs_host:
    hostname: "{{ vcenter }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ item.esxi_hostname }}.{{ domainname }}"
    switch_name: "{{ vmotion_dvswitch }}"
    vmnics:
        - vmnic2
        - vmnic3
    state: present
    validate_certs: no
  with_items:
   - "{{ vars_hosts }}"
  delegate_to: localhost
- name: Add Host to vMotion dVS
  when: item.cluster == 'ChasApps-Cluster'
  vmware_dvs_host:
    hostname: "{{ vcenter }}"
    username: "{{ vcenter_username }}"
    password: "{{ vcenter_password }}"
    esxi_hostname: "{{ item.esxi_hostname }}.{{ domainname }}"
    switch_name: "{{ chas_vmotion_dvswitch }}"
    vmnics:
        - vmnic2
        - vmnic3
    state: present
    validate_certs: no
  with_items:
   - "{{ vars_hosts }}"
  delegate_to: localhost